name: Shop-CRUD $(Build.BuildId) $(Get-Date -Format yyyyMMddhhmmss)

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    vstsFeed: 'my-vsts-feed' # A series of numbers and letters

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'